### ISSUE TITLE
Add support for array columns

### ISSUE THREAD

**Issue by maxdeviant** [lpil/pgo#12]
While working in [gleam-lang/packages](https://github.com/gleam-lang/packages) I noticed that `gleam_pgo` doesn't seem to support array columns in Postgres.

**Comment by lpil** [comment]
Good idea! Thanks

**Comment by ghivert** [comment]
Array columns can be added easily, coercion is already working. I have a column as `params int[]` in postgres, and all I had to do (to trick `pgo`) was to put the value with `dynamic.unsafe_coerce(dynamic.from([1, 2, 3]))`, and it's working! I think we could add `array: fn (List(a)) -> Value` in `pgo` module directly.

**Comment by lpil** [comment]
Excellent! Let's do it
