### ISSUE TITLE
Can't connect to aiden postgresql

### ISSUE THREAD

**Issue by mine-tech-oficial** [lpil/pgo#16]
Hello! After setting up my connection for a free tier aiden postgresql db with the following code and running it, my console spams `INFO at=Connecting reason=Nxdomain` 15 times, waits a litte, and repeats. Can someone help me?
```pgo.connect(
      pgo.Config(
        ..pgo.default_config(),
        database: "defaultdb",
        host: "[REDACTED].a.aivencloud.com",
        port: 22_381,
        user: "avnadmin",
        password: option.Some("AVNS_SfFgWBrfrtALtds9CCL"),
        ssl: True,
        pool_size: 15,
      ),
    )
```

**Comment by lpil** [comment]
Hello! You'll need to talk to the PGO maintainers here after our debugging session in discord as the issue is not with the Gleam bindings.

**Comment by tsloughter** [comment]
Don't think this ever got to me but I'm happy to help if you can give me access to an aiden db.

But I see `ssl: True` so maybe it is the same as the AWS issue that turned out to be that gleam pgo is missing `ssl_options` in the config so you can't pass it the necessary options.

**Comment by mine-tech-oficial** [comment]
Hi! At the end I just ended up not using Aiven and instead using Neon for now (although that also isn't working), but I think that you can get access to an Aiven DB for free, if you want to test it
