### ISSUE TITLE
Add support for ssl_options

### ISSUE THREAD

**Issue by ejstembler** [lpil/pgo#32]
The gleam version is missing `ssl_options` which is required to connect to Postgres on AWS RDS / GCP Cloud SQL, etc.

**Reference**: [issue 21](https://github.com/lpil/pgo/issues/21)

**Comment by lpil** [comment]
Please do not open duplicate issues, thank you.

**Comment by ejstembler** [comment]
@lpil Any reason this is not planned? I’m just curious…

**Comment by giovannibonetti** [comment]
@ejstembler apparently this is being worked on #22

**Comment by lpil** [comment]
I didn't say it was not planned, this is a duplicate issue.

**Comment by ejstembler** [comment]
> I didn't say it was not planned, this is a duplicate issue.

True. I was going off what the `lpil closed this as not planned` message.  I see now if I hover over `not planned` is says `Won't fix, can't repo, duplicate, stale` which encompasses `duplicate`.  Sorry for my confusion.
