### ISSUE TITLE
Postgres enum support

### ISSUE THREAD

**Issue by isaacharrisholt** [lpil/pgo#40]
Hallo, I'd like to be able to insert Postgres enums with PGO. I've tried inserting them as text to no avail by doing something like:

```sql
$1::enum_type
```

**Comment by lpil** [comment]
Good idea. I'm not sure what the API might be though 🤔

**Comment by isaacharrisholt** [comment]
Honestly `pgo.enum(String)` is probably best, and users can have their own custom type -> string functions if they want them

**Comment by lpil** [comment]
That may require us to generate atoms at runtime, which doesn't seems great. We'll need to look at what PGO does internally.

**Comment by giacomocavalieri** [comment]
I can't seem to replicate the issue, enums work totally fine from my experiments:
```sql
create type mood as enum ('sad', 'ok', 'happy');
create table moods (
   current_mood mood primary key
);
```

```gleam
let assert Ok(pgo.Returned(1, [])) =
  "insert into moods values ($1)"
  |> pgo.execute(db, [pgo.text("happy")], dynamic.dynamic)

let assert Ok(pgo.Returned(1, ["happy"])) =
  "select current_mood from moods"
  |> pgo.execute(db, [], dynamic.element(0, dynamic.string))
  
let assert Ok(pgo.Returned(1, ["happy"])) =
  "select current_mood from moods where current_mood = $1"
  |> pgo.execute(db, [dynamic.text("happy")], dynamic.element(0, dynamic.string))
```

They're always treated as strings, both when used as query params or appear in the returned values

**Comment by lpil** [comment]
Hooray!
